#!/bin/bash


Help()
{
    # Display Help
    echo "A helper function for simulation"
    echo
    echo "E.g. simulation -s"
    echo "options:"
    echo "-s   Sets up the environment for the simulation"
    echo "-c   Removes the venv"
    echo "-b   Builds venv"
    echo "-r   Runs the simulation"
    echo "-h   Displays this help message"
    echo "-i   Installs packages"
    echo "-u   Updates packages"
    echo "-k   Removes packages"
    echo
}

CheckPython()
{
    echo "============= Checking Python version ============="
    # Check if python is installed
    if ! [ -x "$(command -v python)" ]; then
        echo "Error: python is not installed" >&2
        exit 1
    fi
    # Get python version
    python_version=$(python3 -V 2>&1 | cut -d' ' -f2)
    echo "Python version: $python_version"
    # Check if python version is greater than 3.9
    if [ "$python_version" \< "3.8.0" ]; then
        echo "Error: python version needs to be equal or greater than 3.9.10" >&2
        exit 1
    fi

}

Check_venv()
{
    echo "============= Checking venv ============="
     # Check if $VIRTUAL_ENV is set
    if [ -z "$VIRTUAL_ENV" ]; then
        echo "Error: venv is not set. Set it up with -s" >&2
        exit 1
    fi
}


Build(){
    echo "============= Building venv ============="
   Check_venv
    pip install -r requirements.txt
}
Clean(){
    echo "============= Cleaning venv ============="
    # Check if need to deactivate venv
    if [ -n "$VIRTUAL_ENV" ]; then
        deactivate
    fi
    rm -rf venv
}
Setup(){
    echo "============= Setting up simulation ============="
    # Create venv

    Clean
    python3 -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    Build
}

Run(){
    echo "============= Running simulation ============="
    Check_venv
    source venv/bin/activate
    python main.py
    
}
# Pass the arguments to the function Install


Install(){
    echo "============= Installing packages ============="
    Check_venv
    # Print all arguments after the command
    for i in "$@"
    do
        echo "Installing $i"
        pip install $i
    done
    pip freeze > requirements.txt

}
UpdatePackages(){
    echo "============= Updating packages ============="
    Check_venv
    # Print all arguments after the command
    for i in "$@"
    do
        echo "Updating $i"
        pip install --upgrade $i
    done
    pip freeze > requirements.txt
}

RemovePackages(){
    echo "============= Removing packages ============="
    Check_venv
    # Print all arguments after the command
    for i in "$@"
    do
        echo "Removing $i"
        pip uninstall $i
    done
    pip freeze > requirements.txt
}

CheckPython
while getopts "scbrh:i:u:k:" option; do
    case $option in
        h) # display Help
            Help
        exit;;
        s) # setup the environment
            Setup
        exit;;
        c) # clean the environment
            Clean
        exit;;
        b) # build the environment
            Build
        exit;;
        r) # run the simulation
            Run
        exit;;
        i)
        # Pass all arguments after the command to the function Install
            Install "$@"
        exit;;
        u)
        # Pass all arguments after the command to the function UpdatePackages
            UpdatePackages "$@"
        exit;;
        k)
        # Pass all arguments after the command to the function RemovePackages
            RemovePackages "$@"
        exit;;
        
        \?) # incorrect option
            echo "Error: Invalid option"
            Help
        exit;;
    esac
done

Help


